name: Feature Request
description: I'd like to request additional functionality
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Before opening a new issue, take a moment to search through the current open ones.

        ---

  - type: textarea
    id: desc
    attributes:
      label: Description
      description: "Provide a clear and concise description of the feature you'd like to see added"
    validations:
      required: true

  - type: textarea
    id: desc
    attributes:
      label: Proposed Solution
      description: "If you have a specific solution in mind, describe it here"
    validations:
      required: true