name: Feature Request
description: I'd like to request additional functionality
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Before opening a new feature, take a moment to search through the current open ones.

        ---

  - type: textarea
    id: desc
    attributes:
      label: Description
      description: "Describe your idea"
    validations:
      required: true

  - type: textarea
    id: desc
    attributes:
      label: Use case
      description: "Describe how this feature would be useful to you or to other users of the project."
    validations:
      required: true

  - type: textarea
    id: desc
    attributes:
      label: Proposed Solution or alternatives
      description: "If you have a specific solution in mind, describe it here."
    validations:
      required: true
