name: Feature request
description: I'd like to request additional functionality
labels: ["enhancement"]

body:
  - type: checkboxes
    attributes:
      label: Already requested ? *
      description: Before opening a new feature request, please take a moment to search through the current open and closed issues to check if it already exists.
      options:
      - label: I have searched the existing open and closed issues.
        required: true

  - type: textarea
    id: desc
    attributes:
      label: Description
      description: "Describe your idea"
    validations:
      required: true

  - type: textarea
    id: desc
    attributes:
      label: Use case
      description: "Describe how this feature would be useful to you or to other users of the project."
    validations:
      required: true

  - type: textarea
    id: desc
    attributes:
      label: Proposed Solution or alternatives
      description: "If you have a specific solution in mind, describe it here."
    validations:
      required: true